CREATE TABLE  "BRANCH" 
   (	"BRANCH_ID" NUMBER(10,0), 
	"BRANCH_NAME" VARCHAR2(255) NOT NULL , 
	"BRANCH_LOCATION" VARCHAR2(255) NOT NULL , 
	 PRIMARY KEY ("BRANCH_ID")
   )
 
CREATE TABLE  "STAFF" 
   (	"STAFF_ID" NUMBER(10,0), 
	"STAFF_NAME" VARCHAR2(255) NOT NULL , 
	"WORKHOUR" INTERVAL DAY (2) TO SECOND (6) NOT NULL , 
	"STAFF_PHONE" NUMBER(10,0) NOT NULL , 
	"STAFF_EMAIL" VARCHAR2(255) NOT NULL , 
	"STAFF_RANK" NUMBER(10,0) NOT NULL , 
	"BRANCHBRANCH_ID" NUMBER(10,0) NOT NULL , 
	 PRIMARY KEY ("STAFF_ID")
   )
 
ALTER TABLE  "STAFF" ADD CONSTRAINT "FKSTAFF608913" FOREIGN KEY ("BRANCHBRANCH_ID")
	  REFERENCES  "BRANCH" ("BRANCH_ID")
 
CREATE TABLE  "CUSTOMER_ACCOUNT" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(255) NOT NULL, 
	"EMAIL" VARCHAR2(255), 
	"PHONE_NUMBER" NUMBER(10,0) NOT NULL , 
	"RANK" NUMBER(10,0) NOT NULL , 
	"ADDRESS" VARCHAR2(255), 
	"GENDER" VARCHAR2(255), 
	"DATE_OF_BIRTH" DATE NOT NULL , 
	 PRIMARY KEY ("ID")
   )
 
CREATE TABLE  "EVALUATION" 
   (	"RATER" VARCHAR2(255) NOT NULL, 
	"date" DATE NOT NULL , 
	"RATING" FLOAT(10) NOT NULL , 
	"BRANCHBRANCH_ID" NUMBER(10,0) NOT NULL , 
	 PRIMARY KEY ("RATER", "BRANCHBRANCH_ID")
   )
 
ALTER TABLE  "EVALUATION" ADD CONSTRAINT "FKEVALUATION423930" FOREIGN KEY ("BRANCHBRANCH_ID")
	  REFERENCES  "BRANCH" ("BRANCH_ID")
 
CREATE TABLE  "ITEM" 
   (	"ITEM_ID" NUMBER(10,0) NOT NULL , 
	"ITEM_NAME" VARCHAR2(255) NOT NULL , 
	"PRICE" FLOAT(10) NOT NULL , 
	"QUANTITY" NUMBER(10,0) NOT NULL , 
	"MANUFACTURE_DATE" DATE NOT NULL , 
	"EXPIRY_DATE" DATE NOT NULL , 
	"SALE_RATE" FLOAT(10), 
	"SALE_DURATION" DATE, 
	"BRANCHBRANCH_ID" NUMBER(10,0) NOT NULL , 
	 PRIMARY KEY ("ITEM_ID")
   )
 
ALTER TABLE  "ITEM" ADD CONSTRAINT "FKITEM693814" FOREIGN KEY ("BRANCHBRANCH_ID")
	  REFERENCES  "BRANCH" ("BRANCH_ID") 
 
 
CREATE TABLE  "RECEIPT" 
   (	"TRANSACTION_ID" NUMBER(10,0), 
	"TAX_RATE" FLOAT(10) NOT NULL , 
	"TIME_DATE" TIMESTAMP (0) NOT NULL , 
	"PAYMENT_TYPE" VARCHAR2(255) NOT NULL , 
	"BRANCHBRANCH_ID" NUMBER(10,0) NOT NULL , 
	"STAFFSTAFF_ID" NUMBER(10,0) NOT NULL , 
	"CUSTOMER_ACCOUNTID" NUMBER(10,0), 
	 PRIMARY KEY ("TRANSACTION_ID")
   )
 
ALTER TABLE  "RECEIPT" ADD CONSTRAINT "FKRECEIPT183360" FOREIGN KEY ("CUSTOMER_ACCOUNTID")
	  REFERENCES  "CUSTOMER_ACCOUNT" ("ID") 
 
ALTER TABLE  "RECEIPT" ADD CONSTRAINT "FK_receipt_staff" FOREIGN KEY ("STAFFSTAFF_ID")
	  REFERENCES  "STAFF" ("STAFF_ID") 
 
ALTER TABLE  "RECEIPT" ADD CONSTRAINT "FKRECEIPT620466" FOREIGN KEY ("BRANCHBRANCH_ID")
	  REFERENCES  "BRANCH" ("BRANCH_ID") 
 
CREATE TABLE  "RECEIPT_ITEM_LIST" 
   (	"RECEIPTTRANSACTION_ID" NUMBER(10,0) NOT NULL , 
	"ITEM_ID" NUMBER(10,0) NOT NULL , 
	"ITEM_NAME" VARCHAR2(255) NOT NULL , 
	"QUANTITY" NUMBER(10,0) NOT NULL , 
	 PRIMARY KEY ("RECEIPTTRANSACTION_ID", "ITEM_ID")
   )
 
ALTER TABLE  "RECEIPT_ITEM_LIST" ADD CONSTRAINT "FKRECEIPT_IT166760" FOREIGN KEY ("RECEIPTTRANSACTION_ID")
	  REFERENCES  "RECEIPT" ("TRANSACTION_ID") 
 
ALTER TABLE  "RECEIPT_ITEM_LIST" ADD CONSTRAINT "FK_RECEIPT_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES  "ITEM" ("ITEM_ID") 